version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ILL6S9xohqNnqBh9mdpVujJPbfpT98
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: P@ssw0rd